
#define NUM_INSTANCES (1 << 12)
#define DISP_MAP_LOG2 10
#define DISP_MAP_SIZE (1<<DISP_MAP_LOG2)
#define PATCH_SIZE1 7.f
#define PATCH_SIZE2 83.f
#define PATCH_SIZE3 257.f

#define DEFAULT_TESSELATION 16.f
#define DISPLACEMENT_LAMBDA 1.3f
#define FOAM_EXPONENTIAL_DECAY 0.3f
